version: '4.0'
services:
  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

    volumes:
    -   keycloak-db-data:/var/lib/postgres/data
    restart: unless-stopped

  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      - keycloak-db

  app-db:
    image: postgres:14
    container_name: scm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    -   app-db-data:/var/lib/postgresql/data
    ports:
    -   "5432:5432"
    restart: unless-stopped

volumes:
  keycloak-db-data:
  app-db-data:
